# This workflow will deploy a Docker Image on Heroku
# For more information see: https://github.com/marketplace/actions/deploy-to-heroku

name: Deploy to Heroku

on:
  release:
    types: [published]
        
jobs:
  deploy_to_heroku:
    name: Deploy Docker Image on Heroku
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest version of repository
      uses: actions/checkout@v2
    
    - uses: akhileshns/heroku-deploy@v3.5.7
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email:  ${{secrets.HEROKU_EMAIL}}
        usedocker: true
