# This workflow will build a Docker Image
# For more information see: https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images#publishing-images-to-docker-hub

name: Publish Docker Image

on:
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest version of repository
      uses: actions/checkout@v2
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rafhaanshah/springbootcamp
        tag_with_ref: true
        tags: latest
