# This workflow will build and publish a Docker Image to Docker Hub
# It will also build and attach an artifact to the GitHub release
# For more information see: https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images#publishing-images-to-docker-hub
# And: https://github.com/shogo82148/actions-upload-release-asset

name: Publish Image and Artifact

on:
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest version of repository
      uses: actions/checkout@v2
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rafhaanshah/springbootcamp
        tag_with_ref: true
        tags: latest

  push_to_release:
    name: Push JAR to GitHub Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest version of repository
      uses: actions/checkout@v2

    - name: Build JAR
      run: |
          ./gradlew bootJar --no-daemon

    - name: Upload Release Asset
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/gradle/src/build/libs/*.jar
