# This workflow will build and publish a Docker Image to Docker Hub
# It will also build and attach an artifact to the GitHub release
# And sync the master branch to release
# For more information see: https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images#publishing-images-to-docker-hub
# And: https://github.com/shogo82148/actions-upload-release-asset
# And: https://github.com/repo-sync/github-sync

name: Publish Image and Artifact

on:
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest version of repository
      uses: actions/checkout@v2
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rafhaanshah/springbootcamp
        tag_with_ref: true
        tags: latest

  sync_branch:
    name: Sync master branch to release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest version of repository
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/RafhaanShah/Spring-Boot-Camp.git"
          source_branch: "master"
          destination_branch: "release"
          github_token: ${{ github.token }}

#  push_to_release:
#    name: Push JAR to GitHub Release
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout latest version of repository
#      uses: actions/checkout@v2
#
#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
#
#    - name: Build JAR
#      run: |
#          ./gradlew bootJar --no-daemon
#
#    - name: Upload Release Asset
#      uses: shogo82148/actions-upload-release-asset@v1
#      with:
#        upload_url: ${{ github.event.release.upload_url }}
#        asset_path: ./build/libs/*.jar
#        asset_name: springbootcamp.jar
#
#    - name: Download latest API spec
#      run: curl https://raw.githubusercontent.com/RafhaanShah/Spring-Boot-Camp/${{ github.event.release.tag_name }}/api.json -o release_spec.json
#
#    - name: Upload API spec
#      uses: shogo82148/actions-upload-release-asset@v1
#      with:
#        upload_url: ${{ github.event.release.upload_url }}
#        asset_path: ./release_spec.json
#        asset_name: api.json
